<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.0.1
 */

/**
 * Database `search`
 */

/* `search`.`info` */
$info = array(
  array('Company' => 'Apple Inc.','ticker' => 'AAPL','recent' => '289.03','high' => '327.85','low' => '169.50','summary' => 'Apple is one of the world\'s leading consumer electronics and personal computer companies. Apple\'s current place in the global marketplace is a far cry from its humble beginnings, with Steve Jobs, Steve Wozniak and Ronald Wayne selling hand-made personal computer kits in the late \'70s. The company continued to focus on personal computers for the following decades, but in recent years that focus has shifted more to consumer electronics such as the iPhone, iPad, and iPod. However, Apple also sells a range of related software, services and applications, with some of the most prominent non-electronics products being the iCloud, iOS, Mac OS and Apple TV. In addition, the company sells and delivers digital applications and software through its iTunes Store, App Store, iBookstore and Mac App Store.  We located in ONE APPLE PARK WAY, CUPERTINO, California, 95014, United States of America. We generated $53.8 billion annual revenue in 2019.

','detail' => 'As a multinational corporation that designs, manufactures and markets mobile communication and media devices, offers personal computers, portable digital music players, and distributes a variety of related software, services, peripherals, networking solutions, and third-party digital content and applications. Our company was established in 1977 as Apple Computer Inc. We have 137,000 employees as of 2019. Apple has 500+ retail stores. 

','officer1' => 'http://localhost:8080/image/7.png','bio1' => 'Tim Cook - Chief Executive Officer
Tim Cook, in full Timothy D. Cook, (born November 1, 1960, Robertsdale, Alabama, U.S.), an American technology executive who was a chief executive officer (CEO) of the computer manufacturer Apple Inc., (2011-). Also, he is the second-largest individual shareholder with 878,425 shares as of Aug. 24, 2018. Cook graduated from Auburn University in Alabama with a bachelor’s degree in industrial engineering in 1982, and in 1988 he received a master’s in business administration from Duke University in Durham, North Carolina. He worked for the computer manufacturer International Business Machines Corporation (IBM) from 1982 to 1994, with his final position being the director of North American fulfillment. He was subsequently chief operating officer of the reseller division at the computer retailer Intelligent Electronics, Inc. (1994–97), and vice president of corporate materials at the computer manufacturer Compaq Computer Corporation (1997). Apple was on the verge of collapse when founder Steve Jobs rejoined the company in 1997. Cook joined Apple shortly thereafter in 1998 as senior vice president of worldwide operations. n 2000 Cook became senior vice president of worldwide operations, sales, and support, and two years later he became executive vice president of worldwide operations and sales. In January 2009 Jobs took a leave of absence through the end of June in order to recover his health and announced that Cook would be interim CEO. Two months before Jobs’s death in October 2011, he resigned as CEO and was succeeded by Cook.
','officer2' => 'http://localhost:8080/image/8.png','bio2' => 'Craig Federighi - Senior Vice President, Software Engineering
Craig Federighi is Apple’s senior vice president of Software Engineering, reporting to CEO Tim and the company\'s third-largest shareholder with 412,571 shares as of Aug. 9, 2018.. Craig oversees the development of iOS and macOS. His teams are responsible for delivering the software at the heart of Apple’s innovative products, including the user interface, applications, and frameworks. Craig returned to Apple in 2009 to lead macOS engineering, and in 2012 took on responsibility for iOS as well, delivering all subsequent releases of the world’s most advanced desktop and mobile operating systems. Prior to his return, Craig worked at NeXT, followed by Apple, and then spent a decade at Ariba, an internet e-commerce pioneer where he held several roles including chief technology officer. Craig holds a Master of Science degree in Computer Science and a Bachelor of Science in Electrical Engineering and Computer Science from the University of California, Berkeley. 
','officer3' => 'http://localhost:8080/image/9.png','bio3' => 'Katherine Adams - Senior Vice President and General Counsel
Katherine Adams is Apple’s general counsel and senior vice president of Legal and Global Security, reporting to CEO Tim Cook. Kate serves on the company’s executive team and oversees all legal matters, including corporate governance, intellectual property, litigation and securities compliance, global security and privacy. Kate joined Apple from Honeywell in 2017, where she worked for 14 years, most recently as senior vice president and general counsel. At Honeywell, Kate was in charge of the organization’s global legal strategy across more than 100 countries. Prior to joining Honeywell, Kate was a partner at Sidley Austin LLP in New York. Earlier in her career, she served as a law clerk for Supreme Court Justice Sandra Day O’Connor; as a trial attorney for the United States Department of Justice, Appellate Section, Environment and Natural Resources Division; and as a law clerk for Stephen Breyer, then chief judge of the US Court of Appeals for the First Circuit. Kate earned a bachelor’s degree in Comparative Literature from Brown University and a law degree from the University of Chicago Law School.

'),
  array('Company' => 'Amazon','ticker' => 'AMZN','recent' => '1901.09','high' => '2185.95','low' => '1586.57','summary' => 'Amazon always seek to be Earth’s most customer-centric company. We are guided by four principles: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking. In each of our segments, we serve our primary customer sets, consisting of consumers, sellers, developers, enterprises, and content creators. In addition, we provide services, such as advertising to sellers, vendors, publishers, and authors, through programs such as sponsored ads, display, and video advertising. We have organized our operations into three segments: North America, International, and Amazon Web Services (“AWS”). These segments reflect the way the Company evaluates its business performance and manages its operations. We locate in 410 TERRY AVENUE NORTH, SEATTLE, Washington, 98109, United States of America. We generated $70.0 billion annual revenue in 2019.','detail' => 'Amazon was incorporated in 1994 in the state of Washington and reincorporated in 1996 in the state of Delaware. Our principal corporate offices are located in Seattle, Washington. We completed our initial public offering in May 1997 and our common stock is listed on the Nasdaq Global Select Market under the symbol “AMZN.”. However, employment levels fluctuate due to seasonal factors affecting our business. In North America, we have more than 75 fulfillment centers and we employed approximately 798,000 full-time and part-time employees as of December 31, 2019, and approximately 125,000 of them are full-time. 

','officer1' => 'http://localhost:8080/image/4.png','bio1' => 'Jeff Bezos, Amazon CEO: 
Jeff Bezos is the founder and CEO of the e-commerce company. He is an Entrepreneur and e-commerce pioneer Amazon, owner of The Washington Post and founder of the space exploration company Blue Origin. His successful business ventures have made him one of the richest people in the world. Born in 1964 in New Mexico, Bezos had an early love of computers and studied computer science and electrical engineering at Princeton University. After graduation, he worked on Wall Street, and in 1990 he became the youngest senior vice president at the investment firm D.E. Shaw.  Four years later, Bezos quit his lucrative job to open Amazon.com, an online bookstore that became one of the Internet\'s biggest success stories. In 2013, Bezos purchased The Washington Post, and in 2017 Amazon acquired Whole Foods. Jeff Preston Bezos is the Chief Executive Officer of Amazon. He is an American internet and aerospace entrepreneur, media proprietor, and investor. He is best known as the founder, chief executive officer, and president of Amazon. He was born in January 12, 1964 (age 56 years), Albuquerque, NM. His nationality is American. His net worth: 115.7 billion USD (2020). He graduated summa cum laude from Princeton University in 1986 with a degree in computer science and electrical engineering., 
','officer2' => 'http://localhost:8080/image/5.png','bio2' => 'Jeff Wilke, CEO of worldwide consumer:
Jeffrey A. Wilke is the CEO of Worldwide Consumer. Jeff Wilke has served as CEO Worldwide Consumer since April 2016. From February 2012 to April 2016, Jeff served as Senior Vice President, Consumer Business, from January 2007 until February 2012, he served as Senior Vice President, North American Retail, and from January 2002 until December 2006, he was Senior Vice President, Worldwide Operations. Jeff joined Amazon.com as Vice President and General Manager, Operations in September 1999. He left AlliedSignal (now Honeywell) where he was Vice-President and General Manager, Pharmaceutical Fine Chemicals. Jeff spent the preceding six years in a variety of operations and general management assignments in the chemical, polymer, and electronics industries. Jeff did his graduate work (MBA and MS in Chemical Engineering) at MIT\'s Leaders for Global Operations (formerly Leaders for Manufacturing) program where he focused on Total Quality and Process Improvement techniques. He began his working career writing software and leading software development at Andersen Consulting (now Accenture). Jeff also holds a BSE degree in Chemical Engineering, Summa Cum Laude, from Princeton University.

','officer3' => 'http://localhost:8080/image/6.png','bio3' => 'Andy Jassy, AWS CEO:
Chief Executive Officer, Amazon Web Services
Andy Jassy is CEO of Amazon Web Services (AWS), the world’s most comprehensive and broadly adopted cloud platform. Having led AWS since its inception, he’s managed an inventive and nimble team that has delivered more than 90 cloud infrastructure and application services that are used by millions of startup, enterprise, and government customers around the world. Jassy joined Amazon in 1997. Prior to founding AWS, he held various leadership roles across the company. He has an AB from Harvard University and an MBA from Harvard Business School.

'),
  array('Company' => 'Tesla, Inc.','ticker' => 'TSLA','recent' => '703.48','high' => '968.99','low' => '176.99','summary' => 'Tesla formerly known as Tesla Motors—is one of the most innovative technology companies in the world. The company focuses, develops, manufactures, sells and leases high-performance fully electric vehicles and energy generation and storage systems, and offers services related to our products. We located in 3500 DEER CREEK RD, PALO ALTO, California, 94304, United States of America. We generated $24.57 billion annual revenue in 2019. 

','detail' => 'Testa was founded on July 1, 2003, by engineers Martin Eberhard and Marc Tarpenning. We are the world\'s first vertically integrated sustainable energy company, offering end-to-end clean energy products, including generation, storage, and consumption. We have 48,016 employees as of 2019. Also, our headquartered located in Palo Alto, CA and has 12 office locations across 9 countries. On February 20, 2020, Tesla reached a market capitalization of US$166 billion. ','officer1' => 'http://localhost:8080/image/1.png','bio1' => 'Elon Reeve Musk - the top shareholder of the company 

Elon Reeve Musk FRS is the CEO of Tesla with 38.6 million shares. He is also an engineer, industrial designer, and technology entrepreneur. He is a citizen of South Africa, Canada, and the United States. He was Born: June 28, 1971 (age 48 years), Pretoria, South Africa. His citizenship in South Africa (1971–present); Canada (1989–present); United States (2002–present). His personal net worth is 36.6 billion USD (2020). 


','officer2' => 'http://localhost:8080/image/2.png','bio2' => 'Jeffrey B. Straubel - the second-largest individual shareholders.

Jeffrey Brian Straubel is part of the founding team of Tesla Inc. He was the inaugural Chief Technical Officer until moving to an advisory role in July 2019. At Tesla, Straubel oversaw the technical and engineering design of the vehicles. He was born on December 20, 1975 (age 44 years), Des Moines, IA. His spouse is Boryana Straubel. He graduated from Stanford University

','officer3' => 'http://localhost:8080/image/3.png','bio3' => 'Deepak Ahuja - the third-largest individual shareholders.

Deepak Prabhu Ahuja is a financial executive working in the automotive manufacturing industry. He is most well known for being the former CFO of Tesla. He was born: 1963 (age 57 years), Mumbai, India. And graduated from Carnegie Mellon University, Northwestern University
')
);
